### ISSUE TITLE
SpreadsheetEngineHateosHandlerSpreadsheetDeltaLoadCell fails when selection contains range

### ISSUE THREAD

**Issue by mP1** [mP1/walkingkooka-spreadsheet-server#551]
1 create new spreadsheet
2 update hash to something like http://localhost:3000/#/1/Untitled/cell/M20:N21

```java
java.lang.IllegalArgumentException: Focused selection must only contain a single viewport element but was X2:Y3
	at walkingkooka.spreadsheet.engine.BasicSpreadsheetEngine.windowSelectionCheck(BasicSpreadsheetEngine.java:1134)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at walkingkooka.spreadsheet.engine.BasicSpreadsheetEngine.window(BasicSpreadsheetEngine.java:968)
	at walkingkooka.spreadsheet.engine.SpreadsheetMetadataStampingSpreadsheetEngine.window(SpreadsheetMetadataStampingSpreadsheetEngine.java:227)
	at walkingkooka.spreadsheet.server.engine.http.SpreadsheetEngineHateosHandlerSpreadsheetDeltaLoadCell.window(SpreadsheetEngineHateosHandlerSpreadsheetDeltaLoadCell.java:98)
	at walkingkooka.spreadsheet.server.engine.http.SpreadsheetEngineHateosHandlerSpreadsheetDeltaLoadCell.handleAll(SpreadsheetEngineHateosHandlerSpreadsheetDeltaLoadCell.java:73)
	at walkingkooka.net.http.server.hateos.HateosResourceSelectionAll.dispatch(HateosResourceSelectionAll.java:42)
	at walkingkooka.net.http.server.hateos.HateosResourceMappingRouterBiConsumerRequest.locateHandlerParseRequestBodyAndDispatch(HateosResourceMappingRouterBiConsumerRequest.java:243)
	at walkingkooka.net.http.server.hateos.HateosResourceMappingRouterBiConsumerRequest.methodSupportedTest(HateosResourceMappingRouterBiConsumerRequest.java:201)
	at walkingkooka.net.http.server.hateos.HateosResourceMappingRouterBiConsumerRequest.extractLinkRelation(HateosResourceMappingRouterBiConsumerRequest.java:163)
	at 
```

**Comment by mP1** [comment]
Forgot to rebuild server.
